name: dotnet-build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore DataScribeCSP/DataScribeCSP.csproj

      - name: Build
        run: dotnet build DataScribeCSP/DataScribeCSP.csproj

      - name: Test
        run: dotnet test DSTests/DSTests.csproj

      - name: Publish
        run: dotnet publish DataScribeCSP/DataScribeCSP.csproj -c Release -o /publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: /publish
